spring.application.name=project
spring.datasource.url = jdbc:postgresql://localhost:5432/ToDoDB
spring.datasource.username=postgres
spring.datasource.password =admin

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml